services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/src
        environment:
            FASTAPI_CONFIG_PATH: /src/app.conf
        ports:
            - 8504:8504
        depends_on:
          pseudonym_db:
            condition: service_healthy

    pseudonym_db:
        image: postgres:15
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --user postgres"]
            start_period: 30s
            start_interval: 1s
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5404:5432
